"""add soft delete to events

Revision ID: 4458a7af853c
Revises: 942228ecbd85
Create Date: 2026-10-09 19:26:34.941531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4458a7af853c'
down_revision: Union[str, Sequence[str], None] = '942228ecbd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'is_deleted')
    # ### end Alembic commands ###
