"""add event capacity and price constraints

Revision ID: 48ab372b2082
Revises: 7f690c7e8778
Create Date: 2026-10-10 23:19:54.963372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ab372b2082'
down_revision: Union[str, Sequence[str], None] = '7f690c7e8778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_booking_user_event', 'booking', ['user_id', 'event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_booking_user_event', 'booking', type_='unique')
    # ### end Alembic commands ###
