"""update event table

Revision ID: 942228ecbd85
Revises: 16c32a1d35a6
Create Date: 2026-10-08 23:19:51.528407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942228ecbd85'
down_revision: Union[str, Sequence[str], None] = '16c32a1d35a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('category_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'event', 'category', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'category_id')
    # ### end Alembic commands ###
