"""update event table

Revision ID: f3d3032908a6
Revises: a3c105e271ff
Create Date: 2026-10-08 21:47:46.497170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d3032908a6'
down_revision: Union[str, Sequence[str], None] = 'a3c105e271ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('event_category_id_fkey'), 'event', type_='foreignkey')
    op.drop_column('event', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('event_category_id_fkey'), 'event', 'category', ['category_id'], ['category_id'])
    # ### end Alembic commands ###
